---
- name: Playbook to install NGINX
  hosts: all
  become: true
  gather_facts: no
  update_cache: yes
  tasks:
    - name: Ansible apt install nginx
      apt:
        name: nginx
        state: present

