---
- name: Playbook to install NGINX
  hosts: all
  become: root
  gather_facts: yes
  tasks:
    - name: Ansible apt install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

